### ISSUE TITLE
join next line if no text selected?

### ISSUE THREAD

**Issue by ingernet** [usernamehw/vscode-join-lines#1]
This extension works great if you select lines - but if you have no lines selected, nothing happens. It would be awesome if this worked like Vim - to find the line that the cursor is on, and join the next line with the keyboard shortcut if there is no text selected. (In Vim it's just shift+j, but obviously in this case it would be dictated by the user's keybindings).

I don't know if this would mean refactoring joinLines(), or if it would mean writing a new function like joinNextLine(), but thought I would float the idea out there. I'd do a PR but I'm definitely no good at Typescript.

**Comment by usernamehw** [comment]
ok. From the next version it will join next line when there's only 1 cursor and no selection.
